apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-rest-api
  template:
    metadata:
      labels:
        app: my-rest-api
    spec:
      containers:
        - name: my-rest-api
          image: my-rest-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-rest-api-service
spec:
  type: NodePort
  selector:
    app: my-rest-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030  # You can pick a port in the 30000-32767 range